# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from buyer import Ui_BuyerWindow
from merchant import Ui_MerchantWindow


class Ui_MainWindow(object):
    def __init__(self):
        self.Bwindow = QtWidgets.QMainWindow()
        self.B_UI = Ui_BuyerWindow()
        self.B_UI.setupUi(self.Bwindow)

        self.Mwindow = QtWidgets.QMainWindow()
        self.M_UI = Ui_MerchantWindow()
        self.M_UI.setupUi(self.Mwindow)

    def MainMen(self,active):
        active.close()
        MainWindow.show()

    def showMerchant(self):
        self.M_UI.pushButton.clicked.connect(lambda: self.MainMen(self.Mwindow))
        MainWindow.close()        
        self.Mwindow.show()
    
    def showBuyer(self):
        self.B_UI.pushButton.clicked.connect(lambda: self.MainMen(self.Bwindow))
        MainWindow.close()        
        self.Bwindow.show()



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Team Creovate")
        MainWindow.resize(1536, 864)
        MainWindow.setMinimumSize(QtCore.QSize(1536, 864))
        MainWindow.setMaximumSize(QtCore.QSize(1536, 864))
        MainWindow.setStyleSheet("background-color :#1c1c1c;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Assets/logo.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1340, 800, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1406, 800, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#5bc4ff;")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 400, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"border-radius:20;\n"
"border: 3px solid #0085ff;\n"
"border-color:#0085ffsu;\n"
"background:transparent;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"border-radius:20;\n"
"border: 3px solid #3a9fd9;\n"
"border-color:#0085ffsu;\n"
"background-color:#3A9FD9\n"
"}\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/shop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(212, 212))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 400, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"border-radius:20;\n"
"border: 3px solid #0085ff;\n"
"border-color:#0085ffsu;\n"
"background:transparent;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover{\n"
"border-radius:20;\n"
"border: 3px solid #3a9fd9;\n"
"border-color:#0085ffsu;\n"
"background-color:#3A9FD9\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/buyer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(212, 212))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Team"))
        self.label_3.setText(_translate("MainWindow", "Creovate"))
        self.pushButton.setText(_translate("MainWindow", "    Merchant"))
        self.pushButton.clicked.connect(lambda: self.showMerchant())
        self.pushButton_2.setText(_translate("MainWindow", "       Buyer"))
        self.pushButton_2.clicked.connect(lambda: self.showBuyer())

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
